const productData = [
	{
		id: 1,
		title: 'Classic Cotton Tee',
		price: 24.99,
		category: 'Apparel',
		rating: 4.6,
		stock: 18,
		image: 'https://via.placeholder.com/300x300?text=Classic+Cotton+Tee',
		description: 'A soft everyday t-shirt made from breathable cotton.',
	},
	{
		id: 2,
		title: 'Leather Sneakers',
		price: 79.99,
		category: 'Footwear',
		rating: 4.8,
		stock: 12,
		image: 'https://via.placeholder.com/300x300?text=Leather+Sneakers',
		description: 'Minimal sneakers built for all-day comfort and style.',
	},
	{
		id: 3,
		title: 'Smart Watch Pro',
		price: 149.99,
		category: 'Accessories',
		rating: 4.4,
		stock: 9,
		image: 'https://via.placeholder.com/300x300?text=Smart+Watch+Pro',
		description: 'Track your activity, notifications, and health metrics.',
	},
	{
		id: 4,
		title: 'Noise-Canceling Headphones',
		price: 199.99,
		category: 'Electronics',
		rating: 4.9,
		stock: 7,
		image: 'https://via.placeholder.com/300x300?text=Headphones',
		description: 'Immersive audio with active noise cancellation for focus.',
	},
	{
		id: 5,
		title: 'Everyday Backpack',
		price: 54.99,
		category: 'Bags',
		rating: 4.5,
		stock: 21,
		image: 'https://via.placeholder.com/300x300?text=Everyday+Backpack',
		description: 'Compact storage with room for a laptop and essentials.',
	},
	{
		id: 6,
		title: 'Ceramic Coffee Mug',
		price: 14.99,
		category: 'Home',
		rating: 4.3,
		stock: 34,
		image: 'https://via.placeholder.com/300x300?text=Coffee+Mug',
		description: 'A clean ceramic mug designed for your daily brew.',
	},
]

export default productData
