const userData = [
	{
		id: 1,
		name: 'Aarav Mehta',
		email: 'aarav.mehta@example.com',
		role: 'Customer',
		status: 'Active',
		ordersCompleted: 14,
		totalSpent: 1249.5,
		city: 'Mumbai',
		avatar: 'https://via.placeholder.com/160x160?text=A',
	},
	{
		id: 2,
		name: 'Sara Khan',
		email: 'sara.khan@example.com',
		role: 'Customer',
		status: 'Active',
		ordersCompleted: 8,
		totalSpent: 689.2,
		city: 'Delhi',
		avatar: 'https://via.placeholder.com/160x160?text=S',
	},
	{
		id: 3,
		name: 'Rohit Sharma',
		email: 'rohit.sharma@example.com',
		role: 'Vendor',
		status: 'Pending',
		ordersCompleted: 21,
		totalSpent: 3240.0,
		city: 'Pune',
		avatar: 'https://via.placeholder.com/160x160?text=R',
	},
	{
		id: 4,
		name: 'Priya Nair',
		email: 'priya.nair@example.com',
		role: 'Admin',
		status: 'Active',
		ordersCompleted: 0,
		totalSpent: 0,
		city: 'Bengaluru',
		avatar: 'https://via.placeholder.com/160x160?text=P',
	},
	{
		id: 5,
		name: 'Kabir Singh',
		email: 'kabir.singh@example.com',
		role: 'Customer',
		status: 'Inactive',
		ordersCompleted: 3,
		totalSpent: 249.99,
		city: 'Ahmedabad',
		avatar: 'https://via.placeholder.com/160x160?text=K',
	},
	{
		id: 6,
		name: 'Neha Verma',
		email: 'neha.verma@example.com',
		role: 'Support',
		status: 'Active',
		ordersCompleted: 0,
		totalSpent: 0,
		city: 'Hyderabad',
		avatar: 'https://via.placeholder.com/160x160?text=N',
	},
]

export default userData
